<?php

//Datos de prueba
$data = [
    0 => array(
        "item" => 1,
        "model" => "YR020FB",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 1,
        "unidad" => "UN",
        "valor_unitario" => 25692,00
    ),
    1 => array(
        "item" => 2,
        "model" => "ZR3002A",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 1,
        "unidad" => "UN",
        "valor_unitario" => 25692,00
    ),
    2 => array(
        "item" => 3,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    3 => array(
        "item" => 3,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    4 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    5 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    6 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    7 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    8 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    9 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    10 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    11 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    12 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    13 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
    14 => array(
        "item" => 4,
        "model" => "AB3245P",
        "imagen" => "http://localhost/pdf-plugin/assets/img/img-producto1.jpg",
        "descripcion" => "Marca: KalsteinLiofilizador piloto (sin función de sellado)",
        "cantidad" => 3,
        "unidad" => "UN",
        "valor_unitario" => 25692,00,
    ),
 ];
 ?>